
import mi
import time
import json
import xmltodict

# TODO: Write documentation
# TODO: If a Logical Disk does not have storage space (ex: USB Hub), no values will be shown, and the code will crash.

class MIApp(mi.Application):
    """
    Class that inherits from mi.Application.

    This class automates a configuration of mi.Application
    """
    
    def __init__(self):

        super().__init__()
        
        self.session = super().create_session(
            protocol=mi.PROTOCOL_WMIDCOM
        )
        
        self.serializer = super().create_serializer()

    def executeQuery( self, wmiClass:str, wmiProperties:list[str] ) -> list[dict]:
        """Executes a wmi query

        :param wmiClass: Name of a wmi class.
        :type wmiClass: str
        :param wmiProperties: List of attribute names.
        :type wmiProperties: list[str]
        :return: A list of dictionaries containing the queried data
        :rtype: list
        """

        attributes_string = ",".join(wmiProperties)

        query = self.session.exec_query(
            u"root\\cimv2",
            u"SELECT {} FROM {}".format(attributes_string, wmiClass)
        )

        result_dict = []
        
        while obj := query.get_next_instance():
            result_dict.append( xmltodict.parse(self.serializer.serialize_instance(obj)) )

        query.close()

        extractedData = self.__dataExtraction(result_dict, wmiProperties)
        
        result = self.__typeAssignment( extractedData )

        return result

    def __dataExtraction(self, extractedDict: dict, wmiProperties: list)->list:
        """ Extracts the specified data from the wmi return string

        :param extractedDict: A dictionary that was generated by the wmi query.
        :type extractedDict: dict
        :param wmiProperties: The wmi attributes that were requested
        :type wmiProperties: list
        :return: A json formatted list.
        :rtype: list
        """


        extractedData = []

        for item in extractedDict:

            attribute_extractor = {}

            if type(item) != list:
                item = [item]

            for i in range( len(item) ):
                for prop in item[i]["INSTANCE"]["PROPERTY"]:
                    if prop["@NAME"] in wmiProperties:
                        if "VALUE" in prop.keys():
                            attribute_extractor[prop["@NAME"]] = {
                                "TYPE": prop["@TYPE"],
                                "VALUE": prop["VALUE"]
                            }

                extractedData.append( attribute_extractor ) 
    
        return extractedData

    def __typeAssignment(self, reading: list) -> list:
        """Converts the type of each entry to its correct value.

        :param reading: A json formatted list containing the wmi readings along with the type of each of those attributes.
        :type reading: list
        :raises TypeError: If this error arises that means the type you're trying to extract hasn't been added to the list of possible wmi types. (Please add it!)
        :return: A list containing json formatted data 
        :rtype: list
        """
        converted_readings = []
        for data in reading:
            
            converted_reading = {}

            for attribute in data:
                
                if data[attribute]['TYPE'] == 'string':
                    converted_reading[attribute] = data[attribute]["VALUE"] 

                elif data[attribute]['TYPE'] == 'uint32' or data[attribute]['TYPE'] == 'uint64' or data[attribute]['TYPE'] == 'uint16' or data[attribute]['TYPE'] == 'uint8':
                    converted_reading[attribute] =  int(data[attribute]["VALUE"])

                elif data[attribute]['TYPE'] == 'boolean':
                    
                    if data[attribute]['VALUE'] == 'false':
                        converted_reading[attribute] =  False
    
                    else:
                        converted_reading[attribute] =  True
    
                else:
                    raise TypeError( "In attribute {}, cannot convert the type {} yet, it should be implmented above.".format(attribute, data["TYPE"]) )
            converted_readings.append(converted_reading)
        
        return converted_readings

    def close(self) -> None:
        """Closes the connection to wmi (don't forget to add it)."""
        self.session.close()
        super().close()
