# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  

  
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: ammaraskar/sphinx-action@master
#       with:
#         docs-folder: "docs/"
#         build-command: "make html"
#         pre-build-command: "sphinx-apidocs -e -o ./docs/rstfiles ./scripts"

  docs:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0
      

#       # Runs a single command using the runners shell
#       - name: Install requirements
#         run: pip install 
