# This is a basic workflow to help you get started with Actions

name: Build Docs

# Controls when the action will run. 
on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  docs:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0

      - name: Generate sphinx api docs
        run: sphinx-apidoc -e -o ./docs/rstfiles ./scripts 
        
      - name: Generate html
        run: cd docs && make html
